// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eklauohhkjixqsfajrin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrbGF1b2hoa2ppeHFzZmFqcmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTg2MzUsImV4cCI6MjA3Mzg3NDYzNX0.qmCj_EqP4kNcGkDA_nnlilJw5pQc8UA0oV_cKxQC9S4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});